### ISSUE TITLE
Pobrežné vody

### ISSUE THREAD

**Issue by milossramek** [enu-sav/minimap-creator#14]
Šlo by spraviť (voliteľne) mapy bez zahrnutia pobrežných vôd do územia štátu? Prípadne hranicu pobrežných vôd len nakresliť svetlejšou čiarou ale nezvýrazňovať? Takto sa hranica pobrežia na úrovni štátu vôbec nekreslí a celkove mapa vyzerá inak, ako sme zvyknutí.
Príklad Dánsko:
![image](https://user-images.githubusercontent.com/1151251/207373517-9793692a-d7a9-4b90-99b7-a7610bd68fa7.png)

**Comment by zdila** [comment]
Implemented in 3f965965a9bff29e664ca859c994ae2e6a5ef443
