### ISSUE TITLE
Add position maps for states

### ISSUE THREAD

**Issue by milossramek** [enu-sav/minimap-creator#8]
We would like to have the possibility to create position maps of countries relative to a continent or other selected areas (like Middle East).
Currently, we specify e.g. German region by a dynamically generated pull-down menus with hierarchy:
Austria
  - ...
Germany
  - Bayern
  - ...

So, we would like to add one layer with  continents or other selected area on top.

One possible solution:
1-st level defines just a bounding box named as Europe, Middle East etc (perhaps hardcoded in site in php)
2-nd level specifies any state. So when somebody selects Europe/China, he/she gets map of Europe without any highlighted country.

If somebody selects a 2-nd level item (Europe/Germany),a map of Europe with highlighted Germany is created

If somebody selects a 3-rd level item (Europe/Germany/Bayern) so a map of Germany is created a Bayern highlighted.
Can we get the list of states from the map.sqlite database?

**Comment by zdila** [comment]
Example for highlighting Germany on the map of Europe:

```bash
curl -G 'http://localhost:8080' \
  --data-urlencode "features=borders,landcover" \
  --data-urlencode "width=1200" \
  --data-urlencode "scale=1" \
  --data-urlencode "margin=20" \
  --data-urlencode "place-types=capital" \
  --data-urlencode "highlight-admin-area=Nemecko" \
  --data-urlencode "bbox=-11.43,35,40,71.5" \
  --data-urlencode "border-width-factor=0.5" | display
```

![eug](https://user-images.githubusercontent.com/636095/196646925-ef98d45d-faad-468d-81d1-d15a3521daa2.png)

> Can we get the list of states from the map.sqlite database?

```sql
select distinct country_code, name, name_sk from admin_areas where admin_level = 2;
```
