### ISSUE TITLE
Draw a river with its tributaries and watershed

### ISSUE THREAD

**Issue by milossramek** [enu-sav/minimap-creator#9]
The basic idea is as follows:
Draw a map of Slovakia with a selected river, its tributaries and watershed (e.g Váh). Perhaps the map with coverage and shaded height map should be used. The area outside the watershed should be grayed-out.
However, since rivers do not obey country borders that much, a better result would perhaps be:
Draw watershed of a river (Danube) with its tributaries (Morava, Vah, Inn, Sava ...), within its bounding box, with coverage and shaded height map, including country names. The area outside the watershed should be grayed-out.
Perhaps a new project should be started for this

**Comment by zdila** [comment]
implemented in 452be08069a9f667597faf77248af2fd2740561e

please create additional issues for adjusting the style
